### ISSUE TITLE
Pin doesn't work, TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by EgorIgorevich** [pinterest/widgets#77]
Today I faced with an issue that i can not pin article to any pinterest board from my new account, however it is still possible to pin using old account. 
I do the following: 
0. Be logged in under newly created facebook account (i'm from Ukraine if it matters)
1. Go to this url https://www.pinterest.com/pin/create/button/?description=West%20Coast%20Tournament%202015&media=https%3A%2F%2Fassets.football.com%2Fpages%2F3a1b32a8-d4a8-50c6-a86d-21e75b0a80241439919284.5722-980x480.jpg%3F1439919422&url=https%3A%2F%2Fwww.football.com%2Fen-us%2Fcalifornia-fc%2Fwest-coast-tournament-2015%2F
2. See popup choose board, but it is broken, the following message is in console: 
entryChunk-react-common-20dd8007.js:20 Name: DenzelError
Message: (Pin) [Line 261, Column 13]
  TypeError: Cannot read property 'toLowerCase' of undefined

PS. I can easily share this article if i'm logged in under old account (there is no errors in console).

**Comment by Tobriand** [comment]
This appears to happen with almost anything using the http://uk.pinterest.com/pin/create/button/... api for me, whether the pin button was accessed via embedded code in the site, or in a browser addin. What *does* continue to work, however, is the Chrome Pin It button. I don't know if it is passing the image to Pinterest in the same way though; the appearance is more of a floating DIV than a popup.

**Comment by kentbrew** [comment]
Closing; this is a bug report in the pin create form. (Which should have been fixed.)

**Comment by cartok** [comment]
This still happens for us. Can you tell me why [this](https://www.pinterest.de/pin/create/button/?url=https://www.lights.ie/colourful-led-floor-lamp-mirella-rgb-138558-ie-en.html&media=https://www.lights.ie/img/600/744/resize/7/8/7864d4a712be060e602396a23b1ed1e273d268d8.jpg) url works
but [this](https://www.pinterest.de/pin/create/button/?url=https://www.lights.ie/truncatus-antique-brass-table-lamp-74600-ie-en.html&media=https://www.lights.ie/img/600/744/resize/2/3/2324b5077ffda8920e833e9589fc671b5e6f7a45.jpg) one not?
